name: Report a bug
description: ———
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for reporting this bug!

        Help us replicate and find a fix for the issue by filling in this form.
  - type: textarea
    attributes:
      label: Description
      description: Describe the issue and how to replicate it
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: Any related log output
